services:
  - type: web
    name: hotel-booking-system
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV  
        value: production
      - key: PYTHONPATH
        value: /app
      - key: DATABASE_SOURCE
        value: auto
      - key: GOOGLE_API_KEY
        value: AIzaSyCcVHV8mdeee1cjZ4D0te5XlyrJAyQxGR4
      - key: FIRECRAWL_API_KEY
        value: fc-d59dc4eba8ae49cf8ea57c690e48b273