services:
  - type: web
    name: hotel-booking-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: USE_POSTGRESQL
        value: true
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hotel_booking_db
          property: connectionString